export enum ErrorCode {
  BAD_REQUEST = "BAD_REQUEST",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  ALREADY_MEMBER = "ALREADY_MEMBER",
  PERSONAL_WORKSPACE = "PERSONAL_WORKSPACE",
  INSUFFICIENT_CREDITS = "INSUFFICIENT_CREDITS",
  IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  PAYMENT_GATEWAY_ERROR = "PAYMENT_GATEWAY_ERROR",
  RATE_LIMITED = "RATE_LIMITED",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
}

export const ERROR_STATUS: Record<ErrorCode, number> = {
  [ErrorCode.BAD_REQUEST]: 400,
  [ErrorCode.VALIDATION_FAILED]: 400,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.ALREADY_MEMBER]: 409,
  [ErrorCode.PERSONAL_WORKSPACE]: 409,
  [ErrorCode.INSUFFICIENT_CREDITS]: 409,
  [ErrorCode.IDEMPOTENCY_CONFLICT]: 409,
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.PAYMENT_GATEWAY_ERROR]: 502,
  [ErrorCode.RATE_LIMITED]: 429,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
};

export class ApiError extends Error {
  constructor(
    readonly code: ErrorCode,
    message: string,
    readonly details?: unknown,
  ) {
    super(message);
  }

  get status() {
    return ERROR_STATUS[this.code];
  }
}
